name: Lotto Data Update

on:
  schedule:
    - cron: '30 12 * * 6' # 매주 토요일 한국시간 밤 9시 30분 (UTC 12:30)
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: |
          python update_lotto.py
          ls -l  # 파일 목록을 로그에 출력해서 확인

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 파일이 존재할 때만 git add 실행
          if [ -f lotto_data.json ]; then
            git add lotto_data.json
            git commit -m "Update lotto data" || echo "No changes to commit"
            git push
          else
            echo "lotto_data.json 파일이 생성되지 않아 푸시를 중단합니다."
            exit 1 # 에러 발생시켜서 로그 확인 유도
          fi
